### ISSUE TITLE
MDBottomNavigation Exception

### ISSUE THREAD

**Issue by obrien-james** [kivymd/KivyMD#179]
#### Description of the Bug

My app which uses the MDBottomNavigation widget throws an exception when trying to load. I have tried the Kitchen_sink demo app - from the latest master version which loads fine, but when you select the Bottom Navigation option it throws an exception.

### Code and Logs

```python
from kivy.app import App
from kivymd.app import MDApp
from kivymd.theming import ThemeManager
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.screenmanager import ScreenManager, Screen
from kivymd.uix.stackfloatingbutton import MDStackFloatingButtons
from kivymd.toast.kivytoast.kivytoast import toast

class Container(Screen):
   pass

class RootLayout(BoxLayout):
    pass

class WindowManager(ScreenManager):
   pass

class MainApp(MDApp):

    def __init__(self, **kwargs):
        self.theme_cls.theme_style = "Light"
        self.theme_cls.primary_palette = "BlueGray"
        self.theme_cls.accent_palette = "Gray"
        super().__init__(**kwargs)

    def build(self):
        self.menu_items = [
            {
                "viewclass": "MDMenuItem",
                "text": "Edit Available Procudures",
                "callback": self.callback_for_menu_items,
            },
            {
                "viewclass": "MDMenuItem",
                "text": "Edit Supervisors",
                "callback": self.callback_for_menu_items,
            },
            {
                "viewclass": "MDMenuItem",
                "text": "Edit Vascular Access",
                "callback": self.callback_for_menu_items,
            },
            {
                "viewclass": "MDMenuItem",
                "text": "Summary Screen",
                "callback": self.callback_for_menu_items,
            },
            {
                "viewclass": "MDMenuItem",
                "text": "Export...",
                "callback": self.callback_for_menu_items,
            }
        ]
    def callback_for_menu_items(self, *args):
        if args[0] == "Edit Available Procudures":
            self.root.ids.sm.current = 'editprocedureslist'
        elif args[0] == "Edit Supervisors":
            self.root.ids.sm.current = 'editsupervisors'
        elif args[0] == "Edit Vascular Access":
            self.root.ids.sm.current = 'editvascularaccess'
        elif args[0] == "Summary Screen":
            self.root.ids.sm.current = 'summary'
        elif args[0] == "Export...":
            toast("E X P O R T I N G . . . . ")


    def AddNewProcedure (self):
        self.root.ids.sm.current = 'AddCath'
        toast("New Procedure") 

    def FirstScreen(self):
        self.root.ids.sm.current = 'main'

    def ShowToast(self, message):
        toast(message)

    def build(self):
        self.title = 'Cardiology Logbook'
        return RootLayout()

if __name__ == "__main__":
   MainApp().run() 


kv = """

#:import MDToolbar kivymd.uix.toolbar.MDToolbar
#:import MDBottomNavigation kivymd.uix.bottomnavigation.MDBottomNavigation
#:import MDBottomNavigationItem kivymd.uix.bottomnavigation.MDBottomNavigationItem
#:import MDList kivymd.uix.list.MDList
#:import TwoLineListItem kivymd.uix.list.TwoLineListItem
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import MDDropdownMenu kivymd.uix.menu.MDDropdownMenu

<RootLayout>:
	id: root_container
	orientation: 'vertical'

    MDToolbar:
        id: toolbar
        title: 'Logbook:'
        md_bg_color: app.theme_cls.primary_color
        left_action_items: [['home', lambda x: app.FirstScreen()]]
        right_action_items: [['plus-outline', lambda x: app.AddNewProcedure()],['dots-vertical', lambda x: MDDropdownMenu(items=app.menu_items, width_mult=2.9).open(self)]]

	WindowManager:
		id: sm
		transition: NoTransition()

		Container:
		AddCath:
		EditSupervisors:
		EditProceduresList:
		EditVascularAccess:
		Summary:

<Container>:
	name: 'main'   

    MDBottomNavigation:
        id: panel

        MDBottomNavigationItem:
            name: 'interventional'
            text: 'Intervention'
            icon: 'axis-arrow'

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(20)
                pos_hint: {'center_x': .5, 'center_y': 0.95}

                MDLabel:
                    font_style: 'Body1'
                    theme_text_color: 'Primary'
                    text: 'Interventional Procedures:'
                    halign: 'center'
                MDLabel:
                	font_style: 'Body1'
                	theme_text_color: 'Primary'
                	text: 'This is some more text here ? where it will end up!! !! !! !!'

        MDBottomNavigationItem:
            name: 'ep'
            text: 'Pacing'
            icon: 'battery-charging-50'

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(10)
                pos_hint: {'center_x': .5, 'center_y': .5}

	            MDLabel:
	                font_style: 'Body1'
	                theme_text_color: 'Primary'
	                text: 'EP / Pacing Procedures:'
	                halign: 'center'

        MDBottomNavigationItem:
            name: 'imaging'
            text: 'Imaging'
            icon: 'camera'

            MDLabel:
                font_style: 'Body1'
                theme_text_color: 'Primary'
                text: 'Imaging Procedures'
                halign: 'center'

        MDBottomNavigationItem:
            name: 'misc'
            text: 'Other / Misc'
            icon: 'heart-multiple-outline'

            MDLabel:
                font_style: 'Body1'
                theme_text_color: 'Primary'
                text: 'Other / Miscallaneous Procedures'
                halign: 'center'
"""


class MainApp(App):
    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

The console output shows the following 

```
Traceback (most recent call last):
   File "kivy/properties.pyx", line 532, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1170, in kivy.properties.BoundedNumericProperty.check
 ValueError: MDBottomNavigationHeader.width is below the minimum bound (80)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 76, in call_fn
     setattr(element, key, e_value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 539, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1182, in kivy.properties.BoundedNumericProperty.check
 ValueError: MDBottomNavigationHeader.width is above the maximum bound (168)
 Exception ignored in: 'kivy.properties.observable_list_dispatch'
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 76, in call_fn
     setattr(element, key, e_value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 539, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1182, in kivy.properties.BoundedNumericProperty.check
 ValueError: MDBottomNavigationHeader.width is above the maximum bound (168)
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 532, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1170, in kivy.properties.BoundedNumericProperty.check
 ValueError: MDBottomNavigationHeader.width is below the minimum bound (80)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 696, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 539, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1182, in kivy.properties.BoundedNumericProperty.check
 ValueError: MDBottomNavigationHeader.width is above the maximum bound (168)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main.py", line 82, in <module>
     MainApp().run() 
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/app.py", line 829, in run
     root = self.build()
   File "main.py", line 79, in build
     return RootLayout()
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/widget.py", line 361, in __init__
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/widget.py", line 469, in apply_class_lang_rules
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 538, in apply
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 659, in _apply_rule
     child, crule, rootrule, rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 657, in _apply_rule
     root=rctx['ids']['root'], rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/widget.py", line 469, in apply_class_lang_rules
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 538, in apply
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 659, in _apply_rule
     child, crule, rootrule, rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 655, in _apply_rule
     widget.add_widget(child)
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivymd/uix/bottomnavigation.py", line 553, in add_widget
     self._refresh_tabs()
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivymd/uix/bottomnavigation.py", line 509, in _refresh_tabs
     tab=tab, panel=self, height=tab_bar.height
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivymd/uix/bottomnavigation.py", line 325, in __init__
     super().__init__()
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivymd/uix/button.py", line 723, in __init__
     super().__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivymd/uix/button.py", line 630, in __init__
     super().__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivymd/theming.py", line 907, in __init__
     super().__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/behaviors/button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Frameworks/python/3.6.5/lib/python3.6/site-packages/kivymd/uix/behaviors/backgroundcolorbehavior.py", line 135, in __init__
     super().__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/widget.py", line 361, in __init__
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/uix/widget.py", line 469, in apply_class_lang_rules
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 538, in apply
     rule_children=rule_children)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 707, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 40:
 ...
      38:
      39:    width:
 >>   40:        root.panel.width / len(root.panel.ids.tab_manager.screens)        if len(root.panel.ids.tab_manager.screens) != 0 else root.panel.width
      41:    padding: (dp(12), dp(12))
      42:    on_press:
 ...
 ValueError: MDBottomNavigationHeader.width is above the maximum bound (168)
   File "/Applications/Kivy3.app/Contents/Resources/kivy/kivy/lang/builder.py", line 696, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 539, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1182, in kivy.properties.BoundedNumericProperty.check
```

### Versions

* OS: OSX Catalina 10.15.1
* Python: 3.6.5
* Kivy: v1.11.0
* KivyMD:  v0.103.0

**Comment by HeaTTheatR** [comment]
@obrien-james Are you using `PyDroid` to launch?`

**Comment by HeaTTheatR** [comment]
@obrien-james I had a similar error only when I tried to run examples from the sources  code in the `PayDroid` app.

**Comment by HeaTTheatR** [comment]
On the desktop and android devices, I did not observe such a problem.

**Comment by HeaTTheatR** [comment]
Moreover! You are using deprecated APIs!
https://github.com/HeaTTheatR/KivyMD#api-breaking-changes

**Comment by HeaTTheatR** [comment]
Therefore, you are not using KivyMD: v0.103.0

**Comment by HeaTTheatR** [comment]
Use KivyMD version 0.103.0 and newer APIs. If the error occurs again, open a new question.

**Comment by obrien-james** [comment]
Hi thanks for the rapid response. I'm using the Kivy.app for Mac 

I started my app a while ago as a side project and then only just picked it back up and a new machine. I've downloaded the newer versions and there have been some tweaks that I need to make to my code.  I thought that I was using the new API.

Also the same error occurs when I use the latest kitchen sink 'app'

![MDBottomNavigation](https://user-images.githubusercontent.com/19244448/74190979-19f58380-4c4b-11ea-8d23-bf833f32523d.gif)

**Comment by HeaTTheatR** [comment]
@obrien-james I can not reproduce your error on my computer.

**Comment by HeaTTheatR** [comment]
@obrien-james 
![ezgif-3-adaf025b4ae6 (1)](https://user-images.githubusercontent.com/16930280/74191897-8a110300-4c65-11ea-9417-ed6cd5f5efd6.gif)

**Comment by HeaTTheatR** [comment]
@obrien-james Try reinstalling the KivyMD library

**Comment by obrien-james** [comment]
@HeaTTheatR Thanks, when you say I'm using the wrong API I'm not sure what is wrong. 

This is a similar issue that someone else has raised recently : https://github.com/HeaTTheatR/KivyMD/issues/174

**Comment by obrien-james** [comment]
I'll try re-installing KivyMD as recommended

**Comment by HeaTTheatR** [comment]
@obrien-james I will open your question again. But I can not fix this error because it does not occur on my computer. You can try to fix it yourself.

**Comment by obrien-james** [comment]
I have re-installed, I used the pip install --upgrade --force-reinstall option and this has fixed the issue. 

Thanks for such a quick response 👍

Just as a side note, which APIs am I using that are depreciated? 

Cheers

James

**Comment by HeaTTheatR** [comment]
@obrien-james 
```
#:import MDToolbar kivymd.uix.toolbar.MDToolbar
#:import MDBottomNavigation kivymd.uix.bottomnavigation.MDBottomNavigation
#:import MDBottomNavigationItem kivymd.uix.bottomnavigation.MDBottomNavigationItem
#:import MDList kivymd.uix.list.MDList
#:import TwoLineListItem kivymd.uix.list.TwoLineListItem
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import MDDropdownMenu kivymd.uix.menu.MDDropdownMenu
```

Import of `MD` classes is not needed in `KV`  files.

**Comment by mkc2019** [comment]
This problem hasn't been fixed as of 14th April, 2020. In case anyone stumbled across this problem, here is the reason that is causing it:

The MDBottomNavigationHeader width is supposedly between dp(68) and dp(168). However, if you look into **kivymd.uix.bottomnavigation.MDBottomNavigationHeader**, you shall see the following line (around line 314):

```
width = BoundedNumericProperty(
        0, min=80, max=168, errorhandler=lambda x: small_error_warn(x)
    )
```
This line literally means setting the minimum and maximum to be 68 and 168 **pixel** respectively, which causes problems because pixels are defined differently across different devices. **This is also why the code works for some of you but doesn't work for others.**. We should use density-independent pixel (dp) instead.

To fix this issue, we need to change the rule as following:
```
width = BoundedNumericProperty(
        0, min=dp(80), max=dp(168), errorhandler=lambda x: small_error_warn(x)
    ) 
```

Since this is a library problem, I have to create my own bottom navigation class, copy all the code into it, change this particular line, and use my new own bottom navigation class instead. Hopefully the dev can address this issue and fix it in the upcoming patch.

**Comment by HeaTTheatR** [comment]
@mkc2019 This error has long been fixed in the master branch!

**Comment by mkc2019** [comment]
I just saw that the issue was fixed on 11th March, 2020. Do I need to specify anything in my buildozer.spec to use this newest update?

Both my virtual environment and buildozer is installed this month. In my buildozer, i simply wrote:
`requirements = python3,kivy,kivymd,requests`
And then this Value Error came out. I used pip list on both virtual environment in my project directory and the buildozer directory. Both are using KivyMD 0.104.0. Something to do with PyPI?

**Comment by HeaTTheatR** [comment]
@mkc2019 `requirements = kivy==1.11.1, git+https://github.com/HeaTTheatR/KivyMD.git@master`

**Comment by mkc2019** [comment]
I did that but the same error still pop up. I checked the kivymd file within my .buildozer/android/app/venv/lib/python3.6/site-packages, and that line specifying the NumericBound on width is still there... I am pretty sure the dependencies are rebuilt as I saw it on the command prompt. 

Maybe I am just doing it wrong. How can I update the library buildozer use? Do I need to update the virutalenv in my project directory as well?

**Comment by HeaTTheatR** [comment]
Remove `.buildozer ` directory.
`requirements = kivy==1.11.1, git+https://github.com/HeaTTheatR/KivyMD.git@master`

**Comment by mkc2019** [comment]
Thanks for the suggestion. I will try that when there is time (as rebuilding buildozer takes quite some time, and there are other things I would like to fix first...)

Just being curious, when will the next KivyMD version came out? I tried reinstalling kivyMD into my virtual environment and this line on Numeric Bound still exists. 

More specificlly, when will this change be pushed to PyPI?

**Comment by HeaTTheatR** [comment]
This error has long been fixed in the master branch!
`python3 -m pip install --force-reinstall git+https://github.com/HeaTTheatR/KivyMD.git`

**Comment by mkc2019** [comment]
Yeah that does the trick. Thank you. Still, what is the relationship between this repository and the one in PyPI? Isn't update in the master branch available through PyPI as well?

**Comment by HeaTTheatR** [comment]
In `PyPi`, the package is updated later

**Comment by mkc2019** [comment]
Ok.
Thank you for your support nonetheless!

**Comment by ghost** [comment]
Nice and thanks for that
