### ISSUE TITLE
MDDialog Visual bug when using a rounded dialog whilst changing light/dark mode theme in the app

### ISSUE THREAD

**Issue by JaeLeeBean** [kivymd/KivyMD#573]
### Description of the Bug

Using MDDialog, bound grouped checkboxes using the checkbox wxample in docs to change theme mode. background color differences near the rounded corners when changing theme mode.

Sidenote: the checkboxes also dont automatically change color to suit the theme mode to which I have attached some changed code in the selectioncontrol file.

### Code and Logs

```python
from kivymd.app import MDApp
from kivy.lang import Builder
from kivymd.uix.dialog import MDDialog
from kivymd.uix.button import MDFlatButton
from kivy.uix.floatlayout import FloatLayout

KV = '''
<Check@MDCheckbox>:
    group: 'group'
    size_hint: None, None
    size: dp(48), dp(48)

<LDDialogContent>:
    Check:
        active: True if app.theme_cls.theme_style == 'Light' else False
        pos_hint: {'center_x': .35, 'center_y': .375}
        on_active: app.theme_cls.theme_style = 'Light'
    MDLabel:
        text: "Light"
        pos_hint: {'center_x': .35, 'center_y': .625}
        halign: "center"
        theme_text_color: "Custom"
        text_color: app.theme_cls.disabled_hint_text_color
    MDLabel:
        text: "Dark"
        pos_hint: {'center_x': .65, 'center_y': .625}
        halign: "center" 
        theme_text_color: "Custom"
        text_color: app.theme_cls.disabled_hint_text_color                   
    Check:
        active: True if app.theme_cls.theme_style == 'Dark' else False
        pos_hint: {'center_x': .65, 'center_y': .375}
        on_active: app.theme_cls.theme_style = 'Dark'

FloatLayout:

    MDFlatButton:
        text: "ALERT DIALOG"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.show_ldpick_dialog()
'''


class LDDialogContent(FloatLayout):
    pass

class MainApp(MDApp):
    
    dialog = None
    
    def build(self):
        self.theme_cls.primary_palette = 'Blue'
        return Builder.load_string(KV)
    
    def show_ldpick_dialog(self):
        if not self.dialog:
            self.dialog = MDDialog(
                size_hint_x = 0.8,
                size_hint_y = 0.8,
                radius = [10, 10, 10, 10],
                title = 'Light/Dark Mode',
                type = 'custom',
                content_cls = LDDialogContent(),
                buttons =[
                    MDFlatButton(
                        text='Back', text_color= self.theme_cls.primary_color, on_release= self.closeDialog,
                    ),
                ],
            )
        #self.dialog.set_normal_height()
        self.dialog.open()
    
    def closeDialog(self, inst):
        self.dialog.dismiss()
        self.dialog = None

if __name__ == '__main__':
    MainApp().run()
```

SideNote:
```python

        self.theme_cls.bind(primary_color=self.update_primary_color)
        self.theme_cls.bind(secondary_text_color=self.update_secondary_color) ##added
        self.update_icon()
        self.update_color()

    def update_primary_color(self, instance, value):
        self.selected_color = value

    def update_secondary_color(self, instance, value): ##added
        self.unselected_color = value
```
### Versions

* OS: Windows 10
* Python: 3.7.9
* Kivy: latest
* KivyMD: latest

**Comment by shashi278** [comment]
Your code has an error. Class `Check` is not defined.

**Comment by JaeLeeBean** [comment]
> Your code has an error. Class `Check` is not defined.

Indeed it has. I have corrected it and edited the code.

**Comment by HeaTTheatR** [comment]
@JaeLeeBean 
> Using MDDialog, bound grouped checkboxes using the checkbox wxample in docs to change theme mode. background color differences near the rounded corners when changing theme mode.

This has been fixed in the master branch of the library.

> Sidenote: the checkboxes also dont automatically change color to suit the theme mode to which I have attached some changed code in the selectioncontrol file.

Please create a new issue for this error.

**Comment by Bright-16** [comment]
please to be honest the MDDialog confirmation is not working properly. I litteraly copied the entire code in the docs but it keep giving me this error "Unknown class <CheckLeftWidget>. this problem is not fixed.
